### ISSUE TITLE
Program field in log formatter

### ISSUE THREAD

**Issue by wolffparkinson** [cs91chris/flask_logify#2]
How do we use LOG_APP_NAME for formatting the log files.

I have this inside my config.yaml
`formatters:
  consoleSimple:
    (): flask_logify.formatters.RequestFormatter
    format: "%(program)% [%(asctime)s] [%(levelname)s] : %(message)s"`

Error
`--- Logging error ---
Traceback (most recent call last):
  File "\appdata\local\programs\python\python39\lib\logging\__init__.py", line 434, in format
    return self._format(record)
  File "\appdata\local\programs\python\python39\lib\logging\__init__.py", line 430, in _format
    return self._fmt % record.__dict__
KeyError: 'program'
`
Same with %(PROGRAM)%

**Comment by cs91chris** [comment]
The LOG_APP_NAME is used only for [FlaskSysLogHandler](https://github.com/cs91chris/flask_logify/blob/ef6f05601990367ebb4add001cb076984f5bd4f6/flask_logify/handlers.py#L10) handler that adds the record ident fo syslog. As example, see: [log.yaml](https://github.com/cs91chris/flask_logify/blob/ef6f05601990367ebb4add001cb076984f5bd4f6/example/log.yaml#L21).
In next release I will also add `%(appname)s` (configurable via LOG_APP_NAME) in [RequestFormatter](https://github.com/cs91chris/flask_logify/blob/ef6f05601990367ebb4add001cb076984f5bd4f6/flask_logify/formatters.py#L6), so it can cover other use cases.

**Comment by wolffparkinson** [comment]
That'd be great
